name: studtourizm
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_map: ^3.1.0
  latlong2: ^0.8.1
  mobx: 
  flutter_mobx:
  provider:
  dio: ^5.0.0
  http: ^0.13.5
  geolocator: ^9.0.2
  flutter_map_marker_cluster: ^1.0.2
  flutter_local_notifications: ^13.0.0
  dropdown_button2: ^1.9.2
  rxdart:
  sliding_up_panel: ^2.0.0+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  json_serializable: ^6.1.4
  mobx_codegen:
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_only.png"

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans.ttf

